config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :searches
  root to: 'products#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :variants, dependent: :destroy
	has_one :image, dependent: :destroy
	accepts_nested_attributes_for :image, update_only: true
	accepts_nested_attributes_for :variants, reject_if: :all_blank, allow_destroy: true
	validates :name, presence: true
	validates :price, presence: true

	self.inheritance_column = "not_sti"

	def self.search(search)
		if search
			where(["name LIKE ?","%#{search}%"])
		else
			all
		end
	end
end

app/models/search.rb
class Search < ApplicationRecord
	self.inheritance_column = "not_sti"

    def search_product
        product = Product.all 

        product = product.where(['name LIKE ?', "%#{name}%"]) if name.present?
        product = product.where(['price <= ?', price]) if price.present?

        return product
    end 
end

app/models/variant.rb
class Variant < ApplicationRecord
	belongs_to :product
	validates :name, presence: true, length: { minimum: 1 }
	validates :price, presence: true, length: { minimum: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
	before_action :set_image, only: %i[ show edit ]
	def index
    	@images = Image.all
  	end

  	# GET /products/1 or /products/1.json
  	def show
  	end

  	# GET /products/new
  	def new
	    @image = Image.new
  	end

  	# GET /products/1/edit
  	def edit
  	end

  	private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @image = Image.find(params[:id])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # before_action :set_product, only: %i[ show edit update destroy ]
  before_action :set_product, only: %i[ edit update destroy ]

  # GET /products or /products.json
  def index
    # @products = Product.all
    @products = Product.search(params[:search])
  end

  # GET /products/1 or /products/1.json
  def show
    @product = Product.select(:id, :name, :price).find_by(id: params[:id])

    respond_to do |format|
      format.html { @product }
      format.json { render json: @product, include:
        [
          :image => {only: [:url]},
          :variants => {only: [:id, :name, :price]}
        ]
      }
    end
  end

  # GET /products/new
  def new
    @product = Product.new
    @product.build_image
    @variants = @product.variants.build
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    # using background processing (sidekiq + redis)
    ProductsCleanupJob.perform_now(params[:id])
    # @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(
        :name, :price,
        image_attributes: [:id, :url, :alt, :caption],
        variants_attributes: [:id, :name, :price, :_destroy]
      )
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
    def show
        @search = Search.find(params[:id])
    end 

    def new 
        @search = Search.new
        @prices = Product.distinct.pluck(:price)
    end

    def create
        @search = Search.create(search_params)
        redirect_to @search
    end 

    private

    def search_params
        params.require(:search).permit(:name, :price, :variant)
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
	def link_to_add_fields(name = nil, f = nil, association = nil, options = nil, html_options = nil, &block)
		# If a block is provided there is no name attribute and the arguments are
		# shifted with one position to the left. This re-assigns those values.
		f, association, options, html_options = name, f, association, options if block_given?

		options = {} if options.nil?
		html_options = {} if html_options.nil?

		if options.include? :locals
			locals = options[:locals]
		else
			locals = { }
		end

		if options.include? :partial
			partial = options[:partial]
		else
			partial = association.to_s.singularize + '_fields'
		end

		# Render the form fields from a file with the association name provided
		new_object = f.object.class.reflect_on_association(association).klass.new
		# id = new_object.object_id
		fields = f.fields_for(association, new_object, child_index: 'addNew') do |builder|
		# fields = f.fields_for(association, new_object, child_index: id) do |builder|
		# fields = f.fields_for(association, new_object) do |builder|
			render(partial, locals.merge!( f: builder))
		end

		# The rendered fields are sent with the link within the data-form-prepend attr
		html_options['data-form-prepend'] = raw CGI::escapeHTML( fields )
		html_options['href'] = '#'

		content_tag(:a, name, html_options, &block)
	end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/variants_helper.rb
module VariantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nestedattr</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
  <%= javascript_pack_tag 'variant' %>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Product field -->
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <!-- Variant field -->
  <div class="field">
    <strong>Variant</strong>
    <%= f.fields_for :variants do |f| %>
      <%= render 'variant_fields', f: f %>
    <% end %> 
    <%= link_to_add_fields 'Add Product Variant', f, :variants %>
  </div>

  <!-- Image attr field -->
  <div class="field">
    <strong>Image</strong>
    <%= f.fields_for :image do |f| %>
      <%= render 'image_fields', f: f %>
    <% end %>
  </div>

  <div class="submit">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_image_fields.html.erb
 <%= f.label :url %>
 <%= f.text_field :url %>

 <%= f.label :alt %>
 <%= f.text_field :alt %>
 
 <%= f.label :caption %>
 <%= f.text_field :caption %>

app/views/products/_variant_fields.html.erb
<!-- <div class="new_data"> -->
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :price %>
	<%= f.number_field :price %>
	<%= f.check_box :_destroy %><strong>Delete</strong><br>
<!-- </div> -->

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<%= console %>

<p id="notice"><%= notice %></p>

<h1>Products</h1>
<%= form_with(url: '/products', method: 'get', local: true) do %>
  <%= text_field_tag(:search) %>
  <%= submit_tag("Search") %>
<% end %>
<%= link_to "Advanced Search", new_search_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<img src="<%= @product.image.url %>" loading="lazy" height="250" width=350>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <p id="product-price"><%= @product.price %></p>
</p>

<div>
  <strong>Variant</strong>
  <%= render @product.variants %>
</div>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/searches/new.html.erb
<h1>Advanced Search</h1>

<%= form_with model: @search do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label 'Price (up to)' %>
    <%= f.text_field :price %>

    <!--%= f.label :type % -->
    <!-- %= f.select :type, options_for_select(@types), include_blank: true %><br -->

    <!-- %= f.label :region % -->
    <!-- %= f.select :region, options_for_select(@regions), include_blank: true %><br><br -->

    <%= f.submit "Search" %>
<% end %>

<p><%= link_to "Back", '/products' %></p>

app/views/searches/show.html.erb
<h1>Search Results</h1>
<p><%= link_to "Back", new_search_path %></p>

<% if @search.search_product.empty? %>
    <p>No Product were found.</p>
<% else %>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Price</th>
                <th colspan="2"></th>
            </tr>
        </thead>

        <tbody>
            <% @search.search_product.each do |product| %>
            <tr>
                <td><%= product.name %></td>
                <td><%= product.price %></td>
                <td><%= link_to 'Show', product %></td>
                <td><%= link_to 'Edit', edit_product_path(product) %></td>
                <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
            <% end %>
        </tbody>
    </table>
<% end %>

app/views/variants/_variant.html.erb
<ul>
    <li>
        <button onclick="document.getElementById('product-price').innerHTML = <%= variant.price %>">
        <%= variant.name %></button> | <%= variant.price %>
    </li>
</ul>